name: blending.io
description: Jack of many trades, master of some.
markdown: kramdown

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/8309911?s=200&v=4

remote_theme: macrod68/jekyll-materialize-starter-template
